### PR TITLE
Fix: reset-password emails use localhost; align Keycloak hostname (closes #66)

### LINKED ISSUE #66: Fix Reset Password Links
#### Explanation: 
```javascript
return {
    emailSent: true,
    forgotPasswordEntryUrl:
      ${base}/realms/${realm}/protocol/openid-connect/auth +
      ?client_id=${encodeURIComponent(clientId)} +
      &redirect_uri=${redirect} +
      &response_type=code&scope=openid,
    accountUrl: ${base}/realms/${realm}/account,
  };
```

This is the current link being sent to the email however, reset password links still use the internal Keycloak URL (`keycloak:8080`) instead of the public URL (`localhost:8080`). 

And even if that were fixed, and the user entered the application from the normal login [Login URL](http://localhost:8080/realms/EMS-realm/protocol/openid-connect/auth?client_id=ems-frontend&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fpassword-updated&response_type=code&scope=openid
), the only way for them to reset the password is through "Forgot password?" where they need to even re-enter the role as well, which is very inefficient and unclear in showing the "Reset Password" goal.

#### Possible solutions: 
- Force it on next login (Send a notifying email without a link) 
- Give the user a link that, after login, takes them directly to the update-password screen
- Trigger Keycloak to send an action-token email for `UPDATE_PASSWORD`

### PR DESCRIPTION
**Pull request by catsdisownedz**
**Problem (Issue #66)**  
The reset password emails contained links like \http://keycloak:8080/.../action-token\, which are not reachable from the browser. In relaxed hostname mode, Keycloak derives the link host from the **request Host header**. Our backend called the admin API at the internal service URL (\keycloak:8080\), so that host was baked into emails. Even when entering via the normal Login URL, the UX required users to click “Forgot password?” and re-enter role info—confusing and inefficient.

**What changed**  
1) **Use public base for execute-actions-email**  
   - For the UPDATE_PASSWORD email, the backend now calls Keycloak using **publicBaseUrl** (\http://localhost:8080\).  
   - This makes the request Host header \localhost:8080\, so KC generates public links.

2) **Hostname config (dev)**
   - Added notes / sample compose for:
     - KC_HTTP_ENABLED=true
     - KC_HOSTNAME=localhost
     - KC_HOSTNAME_URL=http://localhost:8080
     - KC_HOSTNAME_ADMIN_URL=http://localhost:8080
   - (Strict can be enabled locally if desired; when strict is on, KC ignores Host headers and always uses the configured hostname.)

3) **No change to redirect URIs**
   - SPA redirect remains \http://localhost:3000/*\ (correct and separate from email link host).

**Why internalBaseUrl wasn’t enough**  
- internalBaseUrl (\http://keycloak:8080\) is right for service-to-service calls and JWT validation, **but** in relaxed mode KC uses the **caller’s Host header** to build email links. Calling from the backend at \keycloak:8080\ led to \keycloak:8080\ in emails.  
- Using publicBaseUrl for this one call (or enabling hostname with localhost) fixes the host in emails.

**Testing**  
- Trigger: POST /v1/admin/users/{id}/reset-password.  
- New email link starts with http://localhost:8080/....  
- Completing the flow redirects to the SPA: http://localhost:3000/password-updated.

**Result**  
- Clear, user-friendly reset path.  
- Emails contain public links.  
- Backend still validates tokens via internal issuer.

### CODE REVIEW

File: src/main/java/com/example/cdr/eventsmanagementsystem/Controller/AdminController/AdminDashboardController.java [hunk 1]
```diff
@@ -3,57 +3,50 @@
...
     @Operation(summary = "Get dashboard statistics", description = "Retrieves statistics for the dashboard")
     @GetMapping(AdminControllerConstants.ADMIN_DASHBOARD_URL)
     public ResponseEntity<DashboardStatisticsDto> dashboard() {
-    DashboardStatisticsDto dto = new DashboardStatisticsDto();
+        // Start with DB-derived stats (totals, utilization, revenue)
+        DashboardStatisticsDto dto = statistics.getDashboardStatistics();
 
-        // ---- USERS (from Keycloak) ----
+        // Overwrite the user counts with Keycloak (if you prefer KC as source of truth)
         Map<String, Long> c = keycloakAdminService.countUsersByRole();
```
Comment (MohamedShawky85) [inline src/main/java/com/example/cdr/eventsmanagementsystem/Controller/AdminController/AdminDashboardController.java:43]: Please use a descriptive variables

File: src/main/java/com/example/cdr/eventsmanagementsystem/Keycloak/KeycloakAdminService.java [hunk 2]
```diff
@@ -252,6 +274,120 @@ public PasswordResetResponse sendResetPasswordAndOptions(String userId) {
...
+        form.add("grant_type", "password");
+        form.add("client_id", props.getAdminClientId()); // usually "admin-cli" (no secret)
+        if (props.getAdminClientSecret() != null && !props.getAdminClientSecret().isBlank()) {
+            form.add("client_secret", props.getAdminClientSecret());
+        }
+        form.add("username", props.getAdminUsername());
+        form.add("password", props.getAdminPassword());
+
+        try {
+            ResponseEntity<Map> resp = restTemplate.postForEntity(tokenUrl, new HttpEntity<>(form, headers), Map.class);
```
Comment (MohamedShawky85) [inline src/main/java/com/example/cdr/eventsmanagementsystem/Keycloak/KeycloakAdminService.java:326]: Try to utilize webclient instead of restTemplate

File: src/main/java/com/example/cdr/eventsmanagementsystem/Service/User/StatisticsManagement.java [hunk 3]
```diff
@@ -62,29 +77,64 @@ public DashboardStatisticsDto getDashboardStatistics() {
...
+    private java.util.List<UiRevenue> buildUiRevenue() {
+        var rows = eventBookingRepository.sumRevenueByOrganizer();
+
+        var out = new java.util.ArrayList<UiRevenue>(rows.size());
+        for (var r : rows) {
+            String first = r.getFirstName();
+            String last = r.getLastName();
+            String displayName;
+
+            if ((first == null || first.isBlank()) && (last == null || last.isBlank())) {
```
Comment (MohamedShawky85) [inline src/main/java/com/example/cdr/eventsmanagementsystem/Service/User/StatisticsManagement.java:111]: Try to utilize StringUtils.isBlank(first)
Try to use the full descriptive name firstName instead of first

File: src/main/java/com/example/cdr/eventsmanagementsystem/Repository/VenueBookingRepository.java [hunk 4]
```diff
@@ -48,4 +51,55 @@ ORDER BY function('date', COALESCE(b.cancelledAt, b.updatedAt))
...
+    );
+                                      
+    @Query("""
+      select count(distinct vb.venueId)
+      from VenueBooking vb
+      where (vb.paymentStatus in (
+              com.example.cdr.eventsmanagementsystem.Model.Booking.PaymentStatus.CAPTURED,
+              com.example.cdr.eventsmanagementsystem.Model.Booking.PaymentStatus.PARTIALLY_REFUNDED,
+              com.example.cdr.eventsmanagementsystem.Model.Booking.PaymentStatus.AUTHORIZED
+            )
```
[the remark this answers is not in the document]
Comment (catsdisownedz) [reply src/main/java/com/example/cdr/eventsmanagementsystem/Repository/VenueBookingRepository.java:95]: According to my research that syntax isn't allowed in such queries, what do you think?

[the remark this answers is not in the document]
Comment (habibaaymannn) [reply src/main/java/com/example/cdr/eventsmanagementsystem/Repository/VenueBookingRepository.java:95]: Yes, I found two ways to do this:

1. use the enum values directly as strings ('CAPTURED'), check [https://www.slingacademy.com/article/using-enum-in-mysql-8-a-practical-guide/](url)
2. pass the enums as a param list (List.of(PaymentStatus.CAPTURED, …)).

**Review by habibaaymannn — APPROVED** [review]
